/*
 * Copyright 2014 National Bank of Belgium
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package be.nbb.demetra.dfm.output.simulation.utils;

import be.nbb.demetra.dfm.output.simulation.utils.rangeslider.RangeSlider;
import ec.tstoolkit.timeseries.simplets.TsPeriod;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Mats Maggi
 */
public class FilterEvaluationSamplePanel extends javax.swing.JPanel {

    private List<TsPeriod> periods;
    private static final String PERIODS = "periods";

    /**
     * Creates new form FilterEvaluationSamplePanel
     */
    public FilterEvaluationSamplePanel() {
        this(new ArrayList<>());
    }

    public FilterEvaluationSamplePanel(List<TsPeriod> p) {
        initComponents();

        Collections.sort(p);
        this.periods = p;
        
        slider.setPaintTicks(periods.size() < 150);

        slider.setMinimum(0);
        slider.setMaximum(periods.size() - 1);
        slider.setValue(0);
        slider.setUpperValue(slider.getMaximum());

        period1.setText(periods.get(0).toString());
        period2.setText(periods.get(periods.size() - 1).toString());

        slider.addChangeListener((ChangeEvent e) -> {
            RangeSlider s = (RangeSlider) e.getSource();
            period1.setText(periods.get(s.getValue()).toString());
            period2.setText(periods.get(s.getUpperValue()).toString());
        });
    }

    public int getStart() {
        return slider.getValue();
    }

    public int getEnd() {
        return slider.getUpperValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperPanel = new javax.swing.JPanel();
        toPanel = new javax.swing.JPanel();
        toLabel = new javax.swing.JLabel();
        period2 = new javax.swing.JLabel();
        fromPanel = new javax.swing.JPanel();
        fromLabel = new javax.swing.JLabel();
        period1 = new javax.swing.JLabel();
        slider = new be.nbb.demetra.dfm.output.simulation.utils.rangeslider.RangeSlider();

        setMinimumSize(new java.awt.Dimension(376, 81));
        setPreferredSize(new java.awt.Dimension(350, 68));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        upperPanel.setLayout(new java.awt.BorderLayout());

        toPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 6));
        toPanel.setLayout(new javax.swing.BoxLayout(toPanel, javax.swing.BoxLayout.PAGE_AXIS));

        toLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(toLabel, "To");
        toLabel.setAlignmentX(1.0F);
        toPanel.add(toLabel);

        period2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(period2, "TsPeriod2");
        period2.setAlignmentX(1.0F);
        toPanel.add(period2);

        upperPanel.add(toPanel, java.awt.BorderLayout.EAST);

        fromPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 6, 3, 3));
        fromPanel.setLayout(new javax.swing.BoxLayout(fromPanel, javax.swing.BoxLayout.PAGE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(fromLabel, "From");
        fromPanel.add(fromLabel);

        period1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(period1, "TsPeriod1");
        fromPanel.add(period1);

        upperPanel.add(fromPanel, java.awt.BorderLayout.WEST);

        add(upperPanel);

        slider.setMajorTickSpacing(1);
        slider.setMinorTickSpacing(1);
        slider.setPaintTicks(true);
        slider.setSnapToTicks(true);
        slider.setThumbShape(be.nbb.demetra.dfm.output.simulation.utils.rangeslider.RangeSlider.ThumbShape.DROP);
        add(slider);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fromLabel;
    private javax.swing.JPanel fromPanel;
    private javax.swing.JLabel period1;
    private javax.swing.JLabel period2;
    private be.nbb.demetra.dfm.output.simulation.utils.rangeslider.RangeSlider slider;
    private javax.swing.JLabel toLabel;
    private javax.swing.JPanel toPanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

}
